name: irak4
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - contourpy=1.3.2=py310h7f4e7e6_0
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=py310hf4fd40f_0
  - freetype=2.14.1=hce30654_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - greenlet=3.2.4=py310h1af2607_1
  - icu=75.1=hfee45f7_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py310h563d721_2
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.11.0=2_h51639a9_openblas
  - libboost=1.86.0=hf493ff8_4
  - libboost-python=1.86.0=py310hdc87794_4
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=2_hb0561ab_openblas
  - libcxx=21.1.7=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_14
  - libgfortran=15.2.0=h07b0088_14
  - libgfortran5=15.2.0=hdae7583_14
  - libglib=2.86.2=hfe11c1f_1
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=2_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libntlm=1.8=h5505292_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpng=1.6.51=hfab5511_0
  - libpq=18.1=h944245b_2
  - librdkit=2025.09.3=hab8bf10_0
  - libsqlite=3.51.1=h9a5124b_0
  - libtiff=4.7.1=h4030677_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.9=h4a9ca0c_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.6=h4a912ad_0
  - matplotlib=3.10.8=py310hb6292c7_0
  - matplotlib-base=3.10.8=py310h0181960_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - numpy=2.2.6=py310h4d83441_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h25f4b65_1
  - pcre2=10.47=h30297fc_0
  - pillow=12.0.0=py310hce4cfee_2
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - pthread-stubs=0.4=hd74edd7_1002
  - pycairo=1.29.0=py310heb030ba_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.10.19=hcd7f573_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - rdkit=2025.09.3=py310h7b699c0_0
  - readline=8.2=h1d1bf99_2
  - reportlab=4.4.5=py310hfe3a0ae_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - scikit-learn=1.7.2=py310h660f142_0
  - scipy=1.15.2=py310h32ab4ed_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlalchemy=2.0.44=py310hfe3a0ae_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_3
  - tornado=6.5.2=py310hfe3a0ae_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=17.0.0=py310hfe3a0ae_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - zlib-ng=2.3.1=h248ca61_1
  - zstd=1.5.7=hd0aec43_5
  - pip:
      - lxml==6.0.2
      - openbabel==3.1.1
      - plip==3.0.0
prefix: /opt/anaconda3/envs/irak4
